name: CI-ID-Pipline-to-AWS-ElasticBeastalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "adv-it-photomanager-application-packages"
  EB_APPLICATION_NAME      : "MyPython"
  EB_ENVIRONMENT_NAME      : "MyPython-env"
  DEPLOY_PAVKAGE_NAME      : "python_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "us-west-2"

on:
  push:
    branches: [ master ]

jobs:
    my_ci_part:
         runs-on: ubuntu-latest
         
         steps: 
           - name: Git clone our repo
             uses: actions/checkout@v1
            
           - name: Create zip deployment package
             run : zip -r ${{ env.DEPLOY_PAVKAGE_NAME }} ./ -x *.git*
            
           - name: Configure my AWS identials
             uses: aws-actions/configure-aws-credentials@v1
             with:
               aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
               aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
               aws-region           : ${{ env.AWS_REGION_NAME }}
            
           - name: Copy deployment package
             run : aws s3 cp ${{ env.DEPLOY_PAVKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
             
           - name: Print congratulations message
             run : echo "Congratulations you are deploy your first package!"
