# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PhotoManager-github-actions

env:
   APLICATION_NAME: "PhotoManager"
   PACKAGE_NAME   : "PMpack${{github.sha}}"

on:
  push:
    branches: [ master ]

jobs:
  My_verification:

    runs-on: windows-latest

    steps:
    - name: Print Hello Message
      run : echo "hi github"

    - name: List folder
      run : dir
      
     
